import type { CollectionConfig } from 'payload'

export const Showcase: CollectionConfig = {
  slug: 'showcase',
  admin: { useAsTitle: 'title' },
  access: {
    read: () => true,
    create: ({ req }) => req.user?.role === 'admin' || req.user?.role === 'engineer',
    update: ({ req }) => req.user?.role === 'admin' || req.user?.role === 'engineer',
    delete: ({ req }) => req.user?.role === 'admin',
  },
  fields: [
    {
      name: 'slug',
      type: 'text',
      unique: true,
      index: true,
      admin: {
        description: 'URL-safe identifier generated from artist-title (used for scanner upserts)',
      },
    },
    { name: 'title', type: 'text', required: true },
    { name: 'artist', type: 'text' },
    { name: 'genre', type: 'text' },
    {
      name: 'equipment',
      type: 'array',
      label: 'Equipment / Plugins used',
      fields: [{ name: 'item', type: 'text', required: true }],
    },
    {
      name: 'labelBefore',
      type: 'text',
      defaultValue: 'Mix',
      admin: { description: 'Button label for the A (before) version, e.g. "Raw Mix"' },
    },
    {
      name: 'labelAfter',
      type: 'text',
      defaultValue: 'Master',
      admin: { description: 'Button label for the B (after) version, e.g. "Zardonic Master"' },
    },
    {
      name: 'startMarker',
      type: 'number',
      defaultValue: 0,
      admin: { description: 'Playback start position in seconds (e.g. chorus at 01:24 = 84)' },
    },
    {
      name: 'lufsTarget',
      type: 'number',
      defaultValue: -14,
      admin: { description: 'Target integrated loudness (LUFS), e.g. -14 for Spotify' },
    },
    {
      name: 'mobileAudioUrl',
      type: 'text',
      admin: {
        description: 'Optional compressed audio URL (MP3/AAC 320kbps) for mobile devices. Falls back to beforeUrl if omitted.',
      },
    },
    // ── Direct-URL fields (populated by the audio scanner script) ──
    {
      name: 'beforeUrl',
      type: 'text',
      admin: {
        description: 'Direct URL for the mix/demo audio file (set by the scanner script). Takes priority over beforeFile when present.',
      },
    },
    {
      name: 'afterUrl',
      type: 'text',
      admin: {
        description: 'Direct URL for the master audio file (set by the scanner script). Takes priority over afterFile when present.',
      },
    },
    {
      name: 'waveformData',
      type: 'json',
      admin: {
        description: 'Pre-computed waveform peak data for the master file (JSON array of amplitude values, generated by the scanner).',
      },
    },
    // ── Upload-relation fields (populated via the CMS admin UI) ──
    { name: 'beforeFile', type: 'upload', relationTo: 'media' },
    { name: 'afterFile', type: 'upload', relationTo: 'media' },
    { name: 'order', type: 'number', defaultValue: 0 },
    { name: 'active', type: 'checkbox', defaultValue: true },
  ],
}
